learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


# TEMPLATE URL
app_name = 'basic_app'

urlpatterns = [
    url('^register/$', views.register, name='register'),
    url('^login/$', views.user_login, name='user_login'),
    url('^logout/$', views.user_logout, name='user_logout'),
    url('^special/$', views.special, name='special'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from basic_app import views
urlpatterns = [
    url('^$', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    # additional attributes of user
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from basic_app.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm


# for login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    data = {
        'registered': registered,
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'basic_app/registration.html', context=data)


def user_login(request):
    if request.method == 'POST':
        # User has submitted the information here we will verify
        # username and password is correct or not

        # Getting username and password from login page
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Now check whether this username and password is correct
        # with existing user or not

        # authenticate function will do this job of authentication
        # from database of users
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Activated")
        else:
            return HttpResponse("Invalid credentials")
    else:
        # User has opened the login page and yet not submitted credentials
        return render(request, 'basic_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You're logged in. Nice!")

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'basic_app:user_logout' %}">Logout</a>
                <p class="nav-item float-right">{{ user }}</p>
            {% else %}
                <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin Login</a>
                <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>
                <a class="nav-item nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
            {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-4 text-center">Django Level Five</h1>
    </div>
{% endblock %}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">LOGIN</h1>
        <form action="{% url 'basic_app:user_login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">username</label>
                <input id="username" name="username" type="text" class="form-control" placeholder="Enter username"/>
            </div>
            <div class="form-group">
                <label for="password">password</label>
                <input id="password" name="password" type="password" class="form-control" placeholder="Enter password"/>
            </div>
            <button type="submit" class="btn btn-outline-success">Login</button>
        </form>

    </div>
{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}

    {% if registered %}
        <h1 class="display-4 text-center">Thank you for registration</h1>
    {% else %}
        <h1 class="display-5 text-center">Register Here:</h1>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" class="btn btn-outline-success" value="Submit"/>
        </form>
    {% endif %}

{% endblock %}